#include "unity.h"
#include "unity_fixture.h"

TEST_GROUP_RUNNER(Foo)
{
	RUN_TEST_CASE(Foo, basic_COUNTING_On_INT_0);
	RUN_TEST_CASE(Foo, basic_RADIX_On_INT_0);
	RUN_TEST_CASE(Foo, basic_BUBBLE_On2_INT_0);
	RUN_TEST_CASE(Foo, basic_INSERTION_On2_INT_0);
	RUN_TEST_CASE(Foo, basic_SELECTION_On2_INT_0);
	RUN_TEST_CASE(Foo, basic_HEAP_Onlogn_INT_0);
	RUN_TEST_CASE(Foo, basic_MERGE_Onlogn_INT_0);
	RUN_TEST_CASE(Foo, basic_QUICK_Onlogn_INT_0);
	RUN_TEST_CASE(Foo, type_algo_upper_COUNTING_ON_INT_1);
	RUN_TEST_CASE(Foo, type_algo_upper_RADIX_ON_INT_1);
	RUN_TEST_CASE(Foo, type_algo_upper_BUBBLE_ON2_INT_1);
	RUN_TEST_CASE(Foo, type_algo_upper_INSERTION_ON2_INT_1);
	RUN_TEST_CASE(Foo, type_algo_upper_SELECTION_ON2_INT_1);
	RUN_TEST_CASE(Foo, type_algo_upper_HEAP_ONLOGN_INT_1);
	RUN_TEST_CASE(Foo, type_algo_upper_MERGE_ONLOGN_INT_1);
	RUN_TEST_CASE(Foo, type_algo_upper_QUICK_ONLOGN_INT_1);
	RUN_TEST_CASE(Foo, type_algo_lower_COUNTING_on_INT_1);
	RUN_TEST_CASE(Foo, type_algo_lower_RADIX_on_INT_1);
	RUN_TEST_CASE(Foo, type_algo_lower_BUBBLE_on2_INT_1);
	RUN_TEST_CASE(Foo, type_algo_lower_INSERTION_on2_INT_1);
	RUN_TEST_CASE(Foo, type_algo_lower_SELECTION_on2_INT_1);
	RUN_TEST_CASE(Foo, type_algo_lower_HEAP_onlogn_INT_1);
	RUN_TEST_CASE(Foo, type_algo_lower_MERGE_onlogn_INT_1);
	RUN_TEST_CASE(Foo, type_algo_lower_QUICK_onlogn_INT_1);
	RUN_TEST_CASE(Foo, len_1_COUNTING_On_INT_1);
	RUN_TEST_CASE(Foo, len_1_RADIX_On_INT_1);
	RUN_TEST_CASE(Foo, len_1_BUBBLE_On2_INT_1);
	RUN_TEST_CASE(Foo, len_1_INSERTION_On2_INT_1);
	RUN_TEST_CASE(Foo, len_1_SELECTION_On2_INT_1);
	RUN_TEST_CASE(Foo, len_1_HEAP_Onlogn_INT_1);
	RUN_TEST_CASE(Foo, len_1_MERGE_Onlogn_INT_1);
	RUN_TEST_CASE(Foo, len_1_QUICK_Onlogn_INT_1);
	RUN_TEST_CASE(Foo, len_2_COUNTING_On_INT_0);
	RUN_TEST_CASE(Foo, len_2_RADIX_On_INT_0);
	RUN_TEST_CASE(Foo, len_2_BUBBLE_On2_INT_0);
	RUN_TEST_CASE(Foo, len_2_INSERTION_On2_INT_0);
	RUN_TEST_CASE(Foo, len_2_SELECTION_On2_INT_0);
	RUN_TEST_CASE(Foo, len_2_HEAP_Onlogn_INT_0);
	RUN_TEST_CASE(Foo, len_2_MERGE_Onlogn_INT_0);
	RUN_TEST_CASE(Foo, len_2_QUICK_Onlogn_INT_0);
	RUN_TEST_CASE(Foo, len_20_COUNTING_On_INT_0);
	RUN_TEST_CASE(Foo, len_20_RADIX_On_INT_0);
	RUN_TEST_CASE(Foo, len_20_BUBBLE_On2_INT_0);
	RUN_TEST_CASE(Foo, len_20_INSERTION_On2_INT_0);
	RUN_TEST_CASE(Foo, len_20_SELECTION_On2_INT_0);
	RUN_TEST_CASE(Foo, len_20_HEAP_Onlogn_INT_0);
	RUN_TEST_CASE(Foo, len_20_MERGE_Onlogn_INT_0);
	RUN_TEST_CASE(Foo, len_20_QUICK_Onlogn_INT_0);
	RUN_TEST_CASE(Foo, len_21_COUNTING_On_INT_1);
	RUN_TEST_CASE(Foo, len_21_RADIX_On_INT_1);
	RUN_TEST_CASE(Foo, len_21_BUBBLE_On2_INT_1);
	RUN_TEST_CASE(Foo, len_21_INSERTION_On2_INT_1);
	RUN_TEST_CASE(Foo, len_21_SELECTION_On2_INT_1);
	RUN_TEST_CASE(Foo, len_21_HEAP_Onlogn_INT_1);
	RUN_TEST_CASE(Foo, len_21_MERGE_Onlogn_INT_1);
	RUN_TEST_CASE(Foo, len_21_QUICK_Onlogn_INT_1);
}
