name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install cppcheck valgrind
      run: sudo apt-get install cppcheck valgrind
    - name: make apps
      run: make
    - name: make cov
      run: make cov
    - name: make sanitize
      run: make sanitize
    - name: make valgrind
      run: make valgrind
    - name: make cppcheck
      run: make cppcheck
      
    
